const campaignActionTypes = {
    GET_CAMPAIGNS_REQUESTED: "GET_CAMPAIGNS_REQUESTED",
    GET_CAMPAIGNS_SUCCEEDED: "GET_CAMPAIGNS_SUCCEEDED",
    GET_CAMPAIGNS_FAILED: "GET_CAMPAIGNS_FAILED",

    CREATE_CAMPAIGN_REQUESTED: "CREATE_CAMPAIGN_REQUESTED",
    CREATE_CAMPAIGN_SUCCEEDED: "CREATE_CAMPAIGN_SUCCEEDED",
    CREATE_CAMPAIGN_FAILED: "CREATE_CAMPAIGN_FAILED",

    UPDATE_CAMPAIGN_REQUESTED: "UPDATE_CAMPAIGN_REQUESTED",
    UPDATE_CAMPAIGN_SUCCEEDED: "UPDATE_CAMPAIGN_SUCCEEDED",
    UPDATE_CAMPAIGN_FAILED: "UPDATE_CAMPAIGN_FAILED",

    DELETE_CAMPAIGN_REQUESTED: "DELETE_CAMPAIGN_REQUESTED",
    DELETE_CAMPAIGN_SUCCEEDED: "DELETE_CAMPAIGN_SUCCEEDED",
    DELETE_CAMPAIGN_FAILED: "DELETE_CAMPAIGN_FAILED",

};

export default campaignActionTypes;