const csrActionTypes = {
	GET_CSR_REQUESTS_REQUESTED: 'GET_CSR_REQUESTS_REQUESTED',
	GET_CSR_REQUESTS_SUCCEEDED: 'GET_CSR_REQUESTS_SUCCEEDED',
	GET_CSR_REQUESTS_FAILED: 'GET_CSR_REQUESTS_FAILED',

	CREATE_CSR_REQUEST_REQUESTED: 'CREATE_CSR_REQUEST_REQUESTED',
	CREATE_CSR_REQUEST_SUCCEEDED: 'CREATE_CSR_REQUEST_SUCCEEDED',
	CREATE_CSR_REQUEST_FAILED: 'CREATE_CSR_REQUEST_FAILED',

	UPDATE_CSR_REQUEST_REQUESTED: 'UPDATE_CSR_REQUEST_REQUESTED',
	UPDATE_CSR_REQUEST_SUCCEEDED: 'UPDATE_CSR_REQUEST_SUCCEEDED',
	UPDATE_CSR_REQUEST_FAILED: 'UPDATE_CSR_REQUEST_FAILED',

	DELETE_CSR_REQUEST_REQUESTED: 'DELETE_CSR_REQUEST_REQUESTED',
	DELETE_CSR_REQUEST_SUCCEEDED: 'DELETE_CSR_REQUEST_SUCCEEDED',
	DELETE_CSR_REQUEST_FAILED: 'DELETE_CSR_REQUEST_FAILED',

	BOOK_CSR_TREES_REQUESTED: 'BOOK_CSR_TREES_REQUESTED',
	BOOK_CSR_TREES_SUCCEEDED: 'BOOK_CSR_TREES_SUCCEEDED',
	BOOK_CSR_TREES_FAILED: 'BOOK_CSR_TREES_FAILED',
};

export default csrActionTypes;
