const donationActionTypes = {
  GET_DONATIONS_REQUESTED: "GET_DONATIONS_REQUESTED",
  GET_DONATIONS_SUCCEEDED: "GET_DONATIONS_SUCCEEDED",
  GET_DONATIONS_FAILED: "GET_DONATIONS_FAILED",

  CREATE_DONATION_REQUESTED: "CREATE_DONATION_REQUESTED",
  CREATE_DONATION_SUCCEEDED: "CREATE_DONATION_SUCCEEDED",
  CREATE_DONATION_FAILED: "CREATE_DONATION_FAILED",

  UPDATE_DONATION_REQUESTED: "UPDATE_DONATION_REQUESTED",
  UPDATE_DONATION_SUCCEEDED: "UPDATE_DONATION_SUCCEEDED",
  UPDATE_DONATION_FAILED: "UPDATE_DONATION_FAILED",

  DELETE_DONATION_REQUESTED: "DELETE_DONATION_REQUESTED",
  DELETE_DONATION_SUCCEEDED: "DELETE_DONATION_SUCCEEDED",
  DELETE_DONATION_FAILED: "DELETE_DONATION_FAILED",

  ASSIGN_USER_TREES_REQUESTED: "ASSIGN_USER_TREES_REQUESTED",
  ASSIGN_USER_TREES_SUCCEEDED: "ASSIGN_USER_TREES_SUCCEEDED",
  ASSIGN_USER_TREES_FAILED: "ASSIGN_USER_TREES_FAILED",

  CREATE_WORK_ORDER_REQUESTED: "CREATE_WORK_ORDER_REQUESTED",
  CREATE_WORK_ORDER_SUCCEEDED: "CREATE_WORK_ORDER_SUCCEEDED",
  CREATE_WORK_ORDER_FAILED: "CREATE_WORK_ORDER_FAILED",
};

export default donationActionTypes;