const organizationActionTypes = {
    GET_ORGANIZATIONS_REQUESTED: "GET_ORGANIZATIONS_REQUESTED",
    GET_ORGANIZATIONS_SUCCEEDED: "GET_ORGANIZATIONS_SUCCEEDED",
    GET_ORGANIZATIONS_FAILED: "GET_ORGANIZATIONS_FAILED",

    CREATE_ORGANIZATION_REQUESTED: "CREATE_ORGANIZATION_REQUESTED",
    CREATE_ORGANIZATION_SUCCEEDED: "CREATE_ORGANIZATION_SUCCEEDED",
    CREATE_ORGANIZATION_FAILED: "CREATE_ORGANIZATION_FAILED",

    UPDATE_ORGANIZATION_REQUESTED: "UPDATE_ORGANIZATION_REQUESTED",
    UPDATE_ORGANIZATION_SUCCEEDED: "UPDATE_ORGANIZATION_SUCCEEDED",
    UPDATE_ORGANIZATION_FAILED: "UPDATE_ORGANIZATION_FAILED",

    DELETE_ORGANIZATION_REQUESTED: "DELETE_ORGANIZATION_REQUESTED",
    DELETE_ORGANIZATION_SUCCEEDED: "DELETE_ORGANIZATION_SUCCEEDED",
    DELETE_ORGANIZATION_FAILED: "DELETE_ORGANIZATION_FAILED",
};

export default organizationActionTypes;