const plotActionTypes = {
    GET_PLOTS_REQUESTED: "GET_PLOTS_REQUESTED",
    GET_PLOTS_SUCCEEDED: "GET_PLOTS_SUCCEEDED",
    GET_PLOTS_FAILED: "GET_PLOTS_FAILED",

    CREATE_PLOT_REQUESTED: "CREATE_PLOT_REQUESTED",
    CREATE_PLOT_SUCCEEDED: "CREATE_PLOT_SUCCEEDED",
    CREATE_PLOT_FAILED: "CREATE_PLOT_FAILED",

    UPDATE_PLOT_REQUESTED: "UPDATE_PLOT_REQUESTED",
    UPDATE_PLOT_SUCCEEDED: "UPDATE_PLOT_SUCCEEDED",
    UPDATE_PLOT_FAILED: "UPDATE_PLOT_FAILED",

    DELETE_PLOT_REQUESTED: "DELETE_PLOT_REQUESTED",
    DELETE_PLOT_SUCCEEDED: "DELETE_PLOT_SUCCEEDED",
    DELETE_PLOT_FAILED: "DELETE_PLOT_FAILED",
};

export default plotActionTypes;