const plotActionTypes = {
    GET_PLOTS_REQUESTED: "GET_PLOTS_REQUESTED",
    GET_PLOTS_SUCCEEDED: "GET_PLOTS_SUCCEEDED",
    GET_PLOTS_FAILED: "GET_PLOTS_FAILED",

    GET_PLOT_TAGS_REQUESTED: "GET_PLOT_TAGS_REQUESTED",
    GET_PLOT_TAGS_SUCCEEDED: "GET_PLOT_TAGS_SUCCEEDED",
    GET_PLOT_TAGS_FAILED: "GET_PLOT_TAGS_FAILED",

    SEARCH_PLOTS_REQUESTED: "SEARCH_PLOTS_REQUESTED",
    SEARCH_PLOTS_SUCCEEDED: "SEARCH_PLOTS_SUCCEEDED",
    SEARCH_PLOTS_FAILED: "SEARCH_PLOTS_FAILED",

    CREATE_PLOT_REQUESTED: "CREATE_PLOT_REQUESTED",
    CREATE_PLOT_SUCCEEDED: "CREATE_PLOT_SUCCEEDED",
    CREATE_PLOT_FAILED: "CREATE_PLOT_FAILED",

    UPDATE_PLOT_REQUESTED: "UPDATE_PLOT_REQUESTED",
    UPDATE_PLOT_SUCCEEDED: "UPDATE_PLOT_SUCCEEDED",
    UPDATE_PLOT_FAILED: "UPDATE_PLOT_FAILED",

    DELETE_PLOT_REQUESTED: "DELETE_PLOT_REQUESTED",
    DELETE_PLOT_SUCCEEDED: "DELETE_PLOT_SUCCEEDED",
    DELETE_PLOT_FAILED: "DELETE_PLOT_FAILED",

    ASSIGN_PLOTS_REQUESTED: "ASSIGN_PLOTS_REQUESTED",
    ASSIGN_PLOTS_SUCCEEDED: "ASSIGN_PLOTS_SUCCEEDED",
    ASSIGN_PLOTS_FAILED: "ASSIGN_PLOTS_FAILED",
};

export default plotActionTypes;