const pondActionTypes = {
    GET_PONDS_REQUESTED: "GET_PONDS_REQUESTED",
    GET_PONDS_SUCCEEDED: "GET_PONDS_SUCCEEDED",
    GET_PONDS_FAILED: "GET_PONDS_FAILED",

    CREATE_POND_REQUESTED: "CREATE_POND_REQUESTED",
    CREATE_POND_SUCCEEDED: "CREATE_POND_SUCCEEDED",
    CREATE_POND_FAILED: "CREATE_POND_FAILED",

    UPDATE_POND_REQUESTED: "UPDATE_POND_REQUESTED",
    UPDATE_POND_SUCCEEDED: "UPDATE_POND_SUCCEEDED",
    UPDATE_POND_FAILED: "UPDATE_POND_FAILED",

    DELETE_POND_REQUESTED: "DELETE_POND_REQUESTED",
    DELETE_POND_SUCCEEDED: "DELETE_POND_SUCCEEDED",
    DELETE_POND_FAILED: "DELETE_POND_FAILED",
};

export default pondActionTypes;