const treeTypeActionTypes = {
    GET_TREES_REQUESTED: "GET_TREES_REQUESTED",
    GET_TREES_SUCCEEDED: "GET_TREES_SUCCEEDED",
    GET_TREES_FAILED: "GET_TREES_FAILED",

    CREATE_TREE_REQUESTED: "CREATE_TREE_REQUESTED",
    CREATE_TREE_SUCCEEDED: "CREATE_TREE_SUCCEEDED",
    CREATE_TREE_FAILED: "CREATE_TREE_FAILED",

    CREATE_BULK_TREES_REQUESTED: "CREATE_BULK_TREES_REQUESTED",
    CREATE_BULK_TREES_SUCCEEDED: "CREATE_BULK_TREES_SUCCEEDED",
    CREATE_BULK_TREES_FAILED: "CREATE_BULK_TREES_FAILED",

    UPDATE_TREE_REQUESTED: "UPDATE_TREE_REQUESTED",
    UPDATE_TREE_SUCCEEDED: "UPDATE_TREE_SUCCEEDED",
    UPDATE_TREE_FAILED: "UPDATE_TREE_FAILED",

    DELETE_TREE_REQUESTED: "DELETE_TREE_REQUESTED",
    DELETE_TREE_SUCCEEDED: "DELETE_TREE_SUCCEEDED",
    DELETE_TREE_FAILED: "DELETE_TREE_FAILED",

    UN_MAP_TREE_REQUESTED: "UN_MAP_TREE_REQUESTED",
    UN_MAP_TREE_SUCCEEDED: "UN_MAP_TREE_SUCCEEDED",
    UN_MAP_TREE_FAILED: "UN_MAP_TREE_FAILED",

    CHANGE_TREES_PLOT_REQUESTED: "CHANGE_TREES_PLOT_REQUESTED",
    CHANGE_TREES_PLOT_SUCCEEDED: "CHANGE_TREES_PLOT_SUCCEEDED",
    CHANGE_TREES_PLOT_FAILED: "CHANGE_TREES_PLOT_FAILED",
};

export default treeTypeActionTypes;