const treeTypeActionTypes = {
    GET_TREE_TYPES_REQUESTED: "GET_TREE_TYPES_REQUESTED",
    GET_TREE_TYPES_SUCCEEDED: "GET_TREE_TYPES_SUCCEEDED",
    GET_TREE_TYPES_FAILED: "GET_TREE_TYPES_FAILED",

    CREATE_TREE_TYPE_REQUESTED: "CREATE_TREE_TYPE_REQUESTED",
    CREATE_TREE_TYPE_SUCCEEDED: "CREATE_TREE_TYPE_SUCCEEDED",
    CREATE_TREE_TYPE_FAILED: "CREATE_TREE_TYPE_FAILED",
};

export default treeTypeActionTypes;