
const treeImageActionTypes = {
    GET_TREE_IMAGES_REQUESTED: "GET_TREE_IMAGES_REQUESTED",
    GET_TREE_IMAGES_SUCCEEDED: "GET_TREE_IMAGES_SUCCEEDED",
    GET_TREE_IMAGES_FAILED: "GET_TREE_IMAGES_FAILED",
};

export default treeImageActionTypes;