const treeTypeActionTypes = {
    GET_TREE_TYPES_REQUESTED: "GET_TREE_TYPES_REQUESTED",
    GET_TREE_TYPES_SUCCEEDED: "GET_TREE_TYPES_SUCCEEDED",
    GET_TREE_TYPES_FAILED: "GET_TREE_TYPES_FAILED",

    CREATE_TREE_TYPE_REQUESTED: "CREATE_TREE_TYPE_REQUESTED",
    CREATE_TREE_TYPE_SUCCEEDED: "CREATE_TREE_TYPE_SUCCEEDED",
    CREATE_TREE_TYPE_FAILED: "CREATE_TREE_TYPE_FAILED",

    UPDATE_TREE_TYPE_REQUESTED: "UPDATE_TREE_TYPE_REQUESTED",
    UPDATE_TREE_TYPE_SUCCEEDED: "UPDATE_TREE_TYPE_SUCCEEDED",
    UPDATE_TREE_TYPE_FAILED: "UPDATE_TREE_TYPE_FAILED",

    DELETE_TREE_TYPE_REQUESTED: "DELETE_TREE_TYPE_REQUESTED",
    DELETE_TREE_TYPE_SUCCEEDED: "DELETE_TREE_TYPE_SUCCEEDED",
    DELETE_TREE_TYPE_FAILED: "DELETE_TREE_TYPE_FAILED",
};

export default treeTypeActionTypes;