const userGroupActionTypes = {
    CREATE_BULK_USER_GROUP_MAPPING_REQUESTED: "CREATE_BULK_USER_GROUP_MAPPING_REQUESTED",
    CREATE_BULK_USER_GROUP_MAPPING_SUCCEEDED: "CREATE_BULK_USER_GROUP_MAPPING_SUCCEEDED",
    CREATE_BULK_USER_GROUP_MAPPING_FAILED: "CREATE_BULK_USER_GROUP_MAPPING_FAILED",
    
    CREATE_USER_GROUP_MAPPING_REQUESTED: "CREATE_USER_GROUP_MAPPING_REQUESTED",
    CREATE_USER_GROUP_MAPPING_SUCCEEDED: "CREATE_USER_GROUP_MAPPING_SUCCEEDED",
    CREATE_USER_GROUP_MAPPING_FAILED: "CREATE_USER_GROUP_MAPPING_FAILED",

    DELETE_USER_GROUP_MAPPING_REQUESTED: "DELETE_USER_GROUP_MAPPING_REQUESTED",
    DELETE_USER_GROUP_MAPPING_SUCCEEDED: "DELETE_USER_GROUP_MAPPING_SUCCEEDED",
    DELETE_USER_GROUP_MAPPING_FAILED: "DELETE_USER_GROUP_MAPPING_FAILED",
};

export default userGroupActionTypes;