const userGroupActionTypes = {
    CREATE_BULK_USER_GROUP_MAPPING_REQUESTED: "CREATE_BULK_USER_GROUP_MAPPING_REQUESTED",
    CREATE_BULK_USER_GROUP_MAPPING_SUCCEEDED: "CREATE_BULK_USER_GROUP_MAPPING_SUCCEEDED",
    CREATE_BULK_USER_GROUP_MAPPING_FAILED: "CREATE_BULK_USER_GROUP_MAPPING_FAILED",
};

export default userGroupActionTypes;