const userTreeActionTypes = {
    GET_USER_TREES_REQUESTED: "GET_USER_TREES_REQUESTED",
    GET_USER_TREES_SUCCEEDED: "GET_USER_TREES_SUCCEEDED",
    GET_USER_TREES_FAILED: "GET_USER_TREES_FAILED",

    CREATE_USER_TREE_REQUESTED: "CREATE_USER_TREE_REQUESTED",
    CREATE_USER_TREE_SUCCEEDED: "CREATE_USER_TREE_SUCCEEDED",
    CREATE_USER_TREE_FAILED: "CREATE_USER_TREE_FAILED",

    UPDATE_USER_TREE_REQUESTED: "UPDATE_USER_TREE_REQUESTED",
    UPDATE_USER_TREE_SUCCEEDED: "UPDATE_USER_TREE_SUCCEEDED",
    UPDATE_USER_TREE_FAILED: "UPDATE_USER_TREE_FAILED",

    DELETE_USER_TREE_REQUESTED: "DELETE_USER_TREE_REQUESTED",
    DELETE_USER_TREE_SUCCEEDED: "DELETE_USER_TREE_SUCCEEDED",
    DELETE_USER_TREE_FAILED: "DELETE_USER_TREE_FAILED",
};

export default userTreeActionTypes;