const VisitUsersActionTypes = {

  GET_VISIT_USERS_REQUESTED: "GET_VISIT_USERS_REQUESTED",
  GET_VISIT_USERS_SUCCEEDED: "GET_VISIT_USERS_SUCCEEDED",
  GET_VISIT_USERS_FAILED: "GET_VISIT_USERS_FAILED",

  CREATE_VISIT_BULK_USERS_REQUESTED: "CREATE_VISIT_BULK_USERS_REQUESTED",
  CREATE_VISIT_BULK_USERS_SUCCEEDED: "CREATE_VISIT_BULK_USERS_SUCCEEDED",
  CREATE_VISIT_BULK_USERS_FAILED: "CREATE_VISIT_BULK_USERS_FAILED",
  
 
  CREATE_VISIT_USER_REQUESTED: "CREATE_VISIT_USER_REQUESTED",
  CREATE_VISIT_USER_SUCCEEDED: "CREATE_VISIT_USER_SUCCEEDED",
  CREATE_VISIT_USER__FAILED: "CREATE_VISIT_USER__FAILED",

  DELETE_VISIT_USER_REQUESTED: "DELETE_VISIT_USER_REQUESTED",
  DELETE_VISIT_USER_SUCCEEDED: "DELETE_VISIT_USER_SUCCEEDED",
  DELETE_VISIT_USER_FAILED: "DELETE_VISIT_USER_FAILED",
};

export default VisitUsersActionTypes;