const visitActionTypes = {
  GET_VISITS_REQUESTED: "GET_VISITS_REQUESTED",
  GET_VISITS_SUCCEEDED: "GET_VISITS_SUCCEEDED",
  GET_VISITS_FAILED: "GET_VISITS_FAILED",

  CREATE_VISIT_REQUESTED: "CREATE_VISIT_REQUESTED",
  CREATE_VISIT_SUCCEEDED: "CREATE_VISIT_SUCCEEDED",
  CREATE_VISIT_FAILED: "CREATE_VISIT_FAILED",

  UPDATE_VISIT_REQUESTED: "UPDATE_VISIT_REQUESTED",
  UPDATE_VISIT_SUCCEEDED: "UPDATE_VISIT_SUCCEEDED",
  UPDATE_VISIT_FAILED: "UPDATE_VISIT_FAILED",

  DELETE_VISIT_REQUESTED: "DELETE_VISIT_REQUESTED",
  DELETE_VISIT_SUCCEEDED: "DELETE_VISIT_SUCCEEDED",
  DELETE_VISIT_FAILED: "DELETE_VISIT_FAILED",
};

export default visitActionTypes;